### ISSUE TITLE
Ditch the vimrc and just use Vimbox

### ISSUE THREAD

**Issue by chenglou** [Schmavery/dotfiles#1]
https://github.com/jordwalke/VimBox

Yo liek y aren't u using it already @bsansouci @Schmavery

**Comment by Schmavery** [comment]
No way! I always wanted Mac keybindings in vim!

--- Original Message ---

**Comment by chenglou** [comment]
@bsansouci

**Comment by chenglou** [comment]
@bsansouci

**Comment by chenglou** [comment]
ok like whatever man you could totally configure that to map to something else man wtv #@bsansouci

**Comment by chenglou** [comment]
@bsansouci
